[package]
name = "RustyChain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.114"
actix-web = "4.0"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
